import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SidebarContextProvider } from './context/context'
import { Header } from './components/header/header'
import { Sidebar } from './components/sidebar/sidebar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ANVERSO',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SidebarContextProvider>
          <Sidebar />
          <Header />
          {children}
        </SidebarContextProvider>
      </body>
    </html>
  )
}
